OBJS   = crustyvm.o
TARGET = testcvm
CFLAGS = -DCRUSTY_TEST -Wall -Wextra -D_FILE_OFFSET_BITS=64 -ggdb
LDFLAGS =

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $(TARGET) $(OBJS)

all: $(TARGET)

clean:
	rm -f $(TARGET) $(OBJS)

.PHONY: clean
